// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hybridstore.proto

/*
Package hybridstore is a generated protocol buffer package.

It is generated from these files:
	hybridstore.proto

It has these top-level messages:
	VerifyKey
	RevokedTox
	VerifyKeys
	RevokedToxes
*/
package hybridstore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VerifyKey struct {
	Key       []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Desc      string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	ExpiresAt int64  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt" json:"expires_at,omitempty"`
}

func (m *VerifyKey) Reset()                    { *m = VerifyKey{} }
func (m *VerifyKey) String() string            { return proto.CompactTextString(m) }
func (*VerifyKey) ProtoMessage()               {}
func (*VerifyKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VerifyKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *VerifyKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VerifyKey) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *VerifyKey) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *VerifyKey) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type RevokedTox struct {
	Reason    string `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *RevokedTox) Reset()                    { *m = RevokedTox{} }
func (m *RevokedTox) String() string            { return proto.CompactTextString(m) }
func (*RevokedTox) ProtoMessage()               {}
func (*RevokedTox) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RevokedTox) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *RevokedTox) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type VerifyKeys struct {
	M map[uint32]*VerifyKey `protobuf:"bytes,1,rep,name=m" json:"m,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *VerifyKeys) Reset()                    { *m = VerifyKeys{} }
func (m *VerifyKeys) String() string            { return proto.CompactTextString(m) }
func (*VerifyKeys) ProtoMessage()               {}
func (*VerifyKeys) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VerifyKeys) GetM() map[uint32]*VerifyKey {
	if m != nil {
		return m.M
	}
	return nil
}

type RevokedToxes struct {
	M map[string]*RevokedTox `protobuf:"bytes,1,rep,name=m" json:"m,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RevokedToxes) Reset()                    { *m = RevokedToxes{} }
func (m *RevokedToxes) String() string            { return proto.CompactTextString(m) }
func (*RevokedToxes) ProtoMessage()               {}
func (*RevokedToxes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RevokedToxes) GetM() map[string]*RevokedTox {
	if m != nil {
		return m.M
	}
	return nil
}

func init() {
	proto.RegisterType((*VerifyKey)(nil), "VerifyKey")
	proto.RegisterType((*RevokedTox)(nil), "RevokedTox")
	proto.RegisterType((*VerifyKeys)(nil), "VerifyKeys")
	proto.RegisterType((*RevokedToxes)(nil), "RevokedToxes")
}

func init() { proto.RegisterFile("hybridstore.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x49, 0xbb, 0x15, 0xfa, 0x3a, 0x41, 0x83, 0x48, 0x11, 0x84, 0x9a, 0xd3, 0x4e, 0x3d,
	0xcc, 0x8b, 0x78, 0xb2, 0x88, 0x27, 0xf1, 0x12, 0xc4, 0xab, 0x74, 0xeb, 0x13, 0xcb, 0x6c, 0x53,
	0x92, 0x6c, 0x2c, 0x67, 0xff, 0x71, 0x9b, 0xa6, 0xd8, 0x38, 0x76, 0xfb, 0xf2, 0x7d, 0xbc, 0xf7,
	0x7b, 0x1f, 0x81, 0x8b, 0x2f, 0xb3, 0x96, 0x75, 0xa5, 0xb4, 0x90, 0x98, 0x77, 0x52, 0x68, 0xc1,
	0x7e, 0x08, 0xc4, 0xef, 0x28, 0xeb, 0x4f, 0xf3, 0x82, 0x86, 0x9e, 0x43, 0xb8, 0x45, 0x93, 0x92,
	0x8c, 0x2c, 0x17, 0xdc, 0x4a, 0x4a, 0x61, 0xd6, 0x96, 0x0d, 0xa6, 0x41, 0x6f, 0xc5, 0x7c, 0xd0,
	0xd6, 0xab, 0x50, 0x6d, 0xd2, 0xd0, 0x79, 0x56, 0xd3, 0x1b, 0x80, 0x8d, 0xc4, 0x52, 0x63, 0xf5,
	0x51, 0xea, 0x74, 0xd6, 0x27, 0x21, 0x8f, 0x47, 0xa7, 0xd0, 0x36, 0xc6, 0x43, 0x57, 0x4b, 0x54,
	0x36, 0x9e, 0xbb, 0x78, 0x74, 0x0a, 0xcd, 0x9e, 0x00, 0x38, 0xee, 0xc5, 0x16, 0xab, 0x37, 0x71,
	0xa0, 0x57, 0x10, 0xf5, 0x83, 0x4a, 0xb4, 0xc3, 0x21, 0x31, 0x1f, 0x5f, 0x47, 0x8c, 0xe0, 0x88,
	0xc1, 0x3a, 0x80, 0xbf, 0x26, 0x8a, 0x66, 0x40, 0x9a, 0x7e, 0x3e, 0x5c, 0x26, 0x2b, 0x9a, 0x4f,
	0x7e, 0xfe, 0xfa, 0xdc, 0x6a, 0x69, 0x38, 0x69, 0xae, 0x1f, 0x21, 0x72, 0x0f, 0xbf, 0xf6, 0x99,
	0xab, 0x9d, 0xc1, 0x7c, 0x5f, 0x7e, 0xef, 0x5c, 0xef, 0x64, 0x05, 0xd3, 0x06, 0xee, 0x82, 0x87,
	0xe0, 0x9e, 0xb0, 0x1d, 0x2c, 0xa6, 0xb3, 0x51, 0x51, 0x36, 0x31, 0x2f, 0x73, 0x3f, 0xf1, 0xa8,
	0xc5, 0x29, 0x6a, 0xec, 0xa8, 0xb7, 0xff, 0xa9, 0x89, 0xb7, 0xc3, 0xc3, 0xae, 0xa3, 0xe1, 0xeb,
	0xee, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x79, 0x6c, 0xb5, 0xcf, 0x01, 0x00, 0x00,
}
